### ISSUE TITLE
Add support for CI builds in template

### ISSUE THREAD

**Issue by michga** [ui5-community/generator-ui5-library#10]
Hello,

Currently, the template generates a `test` npm script that launches a server and the test suite.
However, the server never stops and this doesn't produce code coverage.
It would be great if this generator could be updated with these 2 "features".

Best regards,
michga

**Comment by petermuessig** [comment]
Hi @michga ,

good point. I will try to see what is possible. Automated testing with Karma is a missing piece here. I added the Karma support to the UI5 library showcase already: https://github.com/ui5-community/ui5-library-showcase/tree/main/packages/ui5-library-showcase

BR,
Peter

**Comment by geert-janklaps** [comment]
@petermuessig,

Just added the karma config to the template (based on the library showcase example). 

Regards,
Geert-Jan

**Comment by petermuessig** [comment]
@geert-janklaps : great! I had this also on my agenda but did not make it till now. Thanks for your help! 😄 

@michga : is this sufficient for you?

**Comment by michga** [comment]
@geert-janklaps - thank you for implementing this!
@petermuessig - it is, thank you
