### ISSUE TITLE
"manifest first approach" - exchange .library for manifest.json file

### ISSUE THREAD

**Issue by wridgeu** [ui5-community/generator-ui5-library#9]
As the readme states "Template library based on the latest best practices template" and with what has been communicated in the latest UI5ers Live, shouldn't we try to use the "manifest first" approach within the generator aswell? 

Sure the `.library` file works and might even look cleaner to some as there isn't as much "unnecessary" information. I think however that we should try to keep the generator similiar to what our examples show/teach.

After all, the `.library` file is a "relict of old times" as Peter stated.

Are there reasons for keeping it anyway (aside from the fact that it is still mentioned [here](https://github.com/SAP/openui5/blob/dc225e1c87bcdfe64e6c67972f6a7bd561cc00d7/docs/controllibraries.md#the-library-file))?

**Comment by petermuessig** [comment]
Hi @wridgeu ,

I kept the `.library` for the moment as I am not yet 100% fine with the manifest-first approach. There are some automated things missing like enhancing the `manifest.json` with the support locales, ... In many cases this is not necessary, so we might get rid of this...

Cheers,
Peter

**Comment by petermuessig** [comment]
Closing this issue for now. We'll align that in future!
